# Copyright © Magento, Inc. All rights reserved.
# See COPYING.txt for license details.

name: CI

on: [pull_request]

jobs:
  unit-tests:
    name: Unit Tests
    runs-on: ubuntu-latest
    steps:
        - name: Run tests
          run: echo 'Test'
